name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -Dspring.profiles.active=prod

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webide3ever:latest .

      - name: Docker Login
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/webide3ever:latest

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
          PROD_DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          PROD_S3_BUCKET_NAME: ${{ secrets.PROD_S3_BUCKET_NAME }}
          PROD_AWS_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          PROD_AWS_SECRET_KEY: ${{ secrets.PROD_AWS_SECRET_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}

        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/webide3ever:latest
          if [ $(sudo docker ps -a -q -f name=web-ide-3ever) ]; then
              sudo docker stop web-ide-3ever
              sudo docker rm web-ide-3ever
          fi
          sudo docker run -d --name web-ide-3ever \
           -p 8080:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/webide3ever:latest \
            --spring.profiles.active=prod \
            --spring.datasource.url=${PROD_DB_URL} \
            --spring.datasource.username=${PROD_DB_USERNAME} \
            --spring.datasource.password=${PROD_DB_PASSWORD} \
            --spring.security.oauth2.client.registration.naver.client-id=${NAVER_CLIENT_ID} \
            --spring.security.oauth2.client.registration.naver.client-secret=${NAVER_CLIENT_SECRET} \
            --spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID} \
            --spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET} \
            --spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID} \
            --spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET} \
            --cloud.aws.s3.bucket-name=${PROD_S3_BUCKET_NAME} \
            --cloud.aws.credentials.access-key=${PROD_AWS_ACCESS_KEY} \
            --cloud.aws.credentials.secret-key=${PROD_AWS_SECRET_KEY} \
          EOF
